#ifndef APP_FLAGS
#define APP_FLAGS

#define LOGIN_COMMAND 15
#define LOGOUT_COMMAND 16
#define REGISTER_COMMAND 17
#define EXIT_COMMAND 30
#define ENTER_GAME_COMMAND 18

#define LOGIN_SUCCESS 27
#define LOGIN_FAIL 28
#define LOGOUT_SUCCESS 29
#define LOGOUT_FAIL 31
#define REGISTER_SUCCESS 32
#define REGISTER_FAIL 33

#define USERNAME_TAKEN 19
#define USERNAME_AVAILABLE 20

#define USER_LOGED_IN 34
#define USER_NOT_LOGED_IN 35

#define ACCOUNT_EXISTS 23
#define ACCOUNT_DOESNT_EXIST 24

#define PASSWORDS_MATCH 21
#define PASSWORDS_DONT_MATCH 22
#define PASSWORD_EXISTS 25
#define PASSWORD_DOESNT_EXIST 26

#define ENTER_GAME_SUCCESS 37
#define GAME_CONFIRM_SUCCESS 36
#define GAME_START 38

#endif // APP_FLAGS
